// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWCr6kKwcZaPCtZ_qxrnV_cyp9pQq323k',
    appId: '1:472099826779:web:4f2933aa747c5df305e37e',
    messagingSenderId: '472099826779',
    projectId: 'mapmyhome-f0728',
    authDomain: 'mapmyhome-f0728.firebaseapp.com',
    storageBucket: 'mapmyhome-f0728.firebasestorage.app',
    measurementId: 'G-KSEMZVSH51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwbzdD-LY9cxz79lioDR9qYAF9pALX9H0',
    appId: '1:472099826779:android:4c6b8e7e9dbbd87a05e37e',
    messagingSenderId: '472099826779',
    projectId: 'mapmyhome-f0728',
    storageBucket: 'mapmyhome-f0728.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAbym87M4kDcmMYMA8U-IfQwWvR3kuU04',
    appId: '1:472099826779:ios:4f7c2bfa545bf9a705e37e',
    messagingSenderId: '472099826779',
    projectId: 'mapmyhome-f0728',
    storageBucket: 'mapmyhome-f0728.firebasestorage.app',
    androidClientId: '472099826779-7scg9f9r8u1js0lace79oc5qc0g5b0sv.apps.googleusercontent.com',
    iosClientId: '472099826779-1bi6esv493m3fd5t27ilvmtlb99mmb07.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapmyhome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAbym87M4kDcmMYMA8U-IfQwWvR3kuU04',
    appId: '1:472099826779:ios:4f7c2bfa545bf9a705e37e',
    messagingSenderId: '472099826779',
    projectId: 'mapmyhome-f0728',
    storageBucket: 'mapmyhome-f0728.firebasestorage.app',
    androidClientId: '472099826779-7scg9f9r8u1js0lace79oc5qc0g5b0sv.apps.googleusercontent.com',
    iosClientId: '472099826779-1bi6esv493m3fd5t27ilvmtlb99mmb07.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapmyhome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWCr6kKwcZaPCtZ_qxrnV_cyp9pQq323k',
    appId: '1:472099826779:web:5a422617e1f7bbb805e37e',
    messagingSenderId: '472099826779',
    projectId: 'mapmyhome-f0728',
    authDomain: 'mapmyhome-f0728.firebaseapp.com',
    storageBucket: 'mapmyhome-f0728.firebasestorage.app',
    measurementId: 'G-K7CNZL5XRS',
  );
}
